export { default as chain } from "./chain.png";
export { default as chest } from "./chest.png";
export { default as chest2 } from "./chest2.png";
export { default as crystals } from "./crystals.png";
export { default as controller } from "./controller.png";
export { default as ninjasupport } from "./ninjasupport.png";
export { default as polygon } from "./polygon.png";
export { default as sllogo } from "./sllogo.png";
export { default as viewer } from "./viewer.png";
